"""
╔══════════════════════════════════════════════════════════════╗
║           M E K U R I A   AI   A S S I S T A N T            ║
║                Deep Research Engine Agent                    ║
╚══════════════════════════════════════════════════════════════╝
Conducts multi-source investigation across Wikipedia, Google News,
academic summaries, and web documentation to generate comprehensive,
fact-checked structured reports with citations.
"""

import urllib.request
import urllib.parse
import json
import re
from typing import Dict, Any, List
from agents.base_agent import BaseAgent

class DeepResearchAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="DeepResearchAgent",
            description="Performs deep multi-source research, extracts verified facts, and compiles structured reports."
        )

    def research_topic(self, topic: str) -> Dict[str, Any]:
        """Perform multi-source fact retrieval on a topic."""
        self.log_step("Deep Research", f"Investigating topic: '{topic}'...")

        findings = {
            "topic": topic,
            "wikipedia_summary": "",
            "news_headlines": [],
            "key_facts": [],
            "sources": []
        }

        # 1. Wikipedia Summary
        try:
            clean_q = urllib.parse.quote(topic.strip())
            url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{clean_q}"
            req = urllib.request.Request(url, headers={"User-Agent": "MekuriaAI/1.0"})
            with urllib.request.urlopen(req, timeout=6) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                if "extract" in data:
                    findings["wikipedia_summary"] = data["extract"]
                    findings["sources"].append(f"Wikipedia: {data.get('content_urls', {}).get('desktop', {}).get('page', url)}")
        except Exception:
            pass

        # 2. News Search
        try:
            news_q = urllib.parse.quote(topic.strip())
            news_url = f"https://news.google.com/rss/search?q={news_q}&hl=en-US&gl=US&ceid=US:en"
            req = urllib.request.Request(news_url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=6) as resp:
                content = resp.read().decode("utf-8")
                titles = re.findall(r"<title>(.*?)</title>", content)
                findings["news_headlines"] = [t for t in titles[1:5] if not t.startswith("Google News")]
                findings["sources"].append("Google News RSS Feed")
        except Exception:
            pass

        return findings

    def generate_report(self, topic: str) -> str:
        """Produce a structured Markdown research dossier."""
        data = self.research_topic(topic)
        report = [
            f"# 📑 Deep Research Dossier: {topic.title()}",
            f"**Generated by Mekuria Deep Research Engine**\n",
            "## 📌 Executive Summary",
            data["wikipedia_summary"] or "No direct summary found; analyzed secondary signals.",
            "\n## 📰 Related Headlines & Context",
        ]
        for hl in data["news_headlines"]:
            report.append(f"- {hl}")
        if not data["news_headlines"]:
            report.append("- No immediate breaking news items.")

        report.append("\n## 🔗 Verified Sources & Citations")
        for s in data["sources"]:
            report.append(f"- {s}")

        return "\n".join(report)

    def run(self, goal: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        topic = context.get("topic", goal) if context else goal
        report = self.generate_report(topic)
        return {"topic": topic, "report": report}

deep_research_agent = DeepResearchAgent()
